version: "3"

services:
  web:
    image: ${DOCKERHUB_IMAGE}
    container_name: ${APP_CONTAINER_NAME}
    networks:
      - nginx-proxy-network
      - 1x1_internal
    restart: unless-stopped
    depends_on:
      - mysql
    env_file:
      - .env.production
  mysql:
    image: mysql:8.0
    container_name: 1x1_mysql
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - 1x1_mysql_data:/var/lib/mysql
    env_file:
      - .env.production
    networks:
      - 1x1_internal

networks:
  nginx-proxy-network:
    external: true
  1x1_internal:
    driver: bridge

volumes:
  1x1_mysql_data:
