version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 1x1_app
    ports:
      - "127.0.0.1:8001:80"
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:8.0
    container_name: 1x1_mysql
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - 1x1_mysql_data:/var/lib/mysql
    env_file:
      - secrets/.env

volumes:
  1x1_mysql_data:
